name: Draft GitHub Release

on:
  push:
    tags:
      - v**

jobs:
  fastlane:
    name: 'Fastlane: Draft GitHub Release'
    runs-on: macOS-latest
    steps:
      - name: Import Certificates
        id: import-certificates
        uses: apple-actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.BUILD_APPLE_CERTIFICATE_P12_BASE64 }}
          p12-password: ${{ secrets.BUILD_APPLE_CERTIFICATE_P12_PASSWORD }}
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.5
          bundler-cache: true
      - uses: maierj/fastlane-action@v2.0.0
        name: Draft Release
        env:
          FASTLANE_USER: ${{ secrets.BUILD_APPLE_USERNAME }}
          FASTLANE_PASSWORD: ${{ secrets.BUILD_APPLE_PASSWORD}}
          FASTLANE_SESSION: ${{ secrets.BUILD_APPLE_SESSION}}
          FASTLANE_TEAM_NAME: ${{ secrets.BUILD_APPLE_TEAM_NAME }}
          FASTLANE_TEAM_ID: ${{ secrets.BUILD_APPLE_TEAM_ID }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.BUILD_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
          CERT_USERNAME: ${{ secrets.BUILD_APPLE_USERNAME }}
          CERT_TEAM_ID: ${{ secrets.BUILD_APPLE_TEAM_ID }}
          CERT_KEYCHAIN_PATH: '/Users/runner/Library/Keychains/signing_temp.keychain-db'
          CERT_KEYCHAIN_PASSWORD: ${{ steps.import-certificates.output.keychain-password }}"
          GYM_EXPORT_TEAM_ID: ${{ secrets.BUILD_APPLE_TEAM_ID }}
          SPARKLE_SIGNING_KEY_BASE64: ${{ secrets.BUILD_SPARKLE_SIGNING_KEY_BASE64 }}
          FL_NOTARIZE_ASC_PROVIDER: ${{ secrets.BUILD_APPLE_TEAM_ID }}
          FL_GITHUB_RELEASE_API_TOKEN: ${{ secrets.BUILD_GITHUB_RELEASE_API_TOKEN }}
        with:
          lane: draft_github_release
